name: "Lint"

on:
    pull_request:
    push:
        branches:
            - main

env:
    fail-fast: true

permissions:
    contents: read

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v5

            - name: PHP-CS-Fixer
              uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.5
              with:
                  args: check --diff --using-cache=no

    twig-cs-fixer:
        name: Twig-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v5

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.5
                  coverage: none
                  tools: composer:v2
                  ini-file: development

            - name: "Cache Composer dependencies"
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache
                  key: composer-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest
                  composer-options: --prefer-dist --prefer-stable

            - name: Run Twig CS Fixer
              run: vendor/bin/twig-cs-fixer check --ansi -v -r github

    linters:
        name: Linters & Static Analysis
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v5

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: intl
                  php-version: 8.5
                  tools: composer:v2

            - name: "Cache Composer dependencies"
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache
                  key: composer-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-

            - name: Lint Composer config
              run: composer validate --no-check-publish --strict

            - name: "Install dependencies"
              id: install
              run: composer install --ansi --no-interaction --no-progress --prefer-dist

            - name: Lint YAML files
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint XLIFF translation files
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:xliff translations

            - name: Lint translation contents
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:translations

            - name: Lint Parameters and Services
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              if: always() && steps.install.outcome == 'success'
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Check if any dependencies are compromised
              if: always() && steps.install.outcome == 'success'
              run: composer audit

            - name: Run PHPStan
              if: always() && steps.install.outcome == 'success'
              run: vendor/bin/phpstan analyze --no-progress --error-format=github
