name: "Tests"

on:
    pull_request:
    push:
        branches:
            - main

env:
    fail-fast: true

permissions:
    contents: read

jobs:
    test:
        name: 'PHPUnit Tests'
        runs-on: 'ubuntu-latest'
        continue-on-error: false

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v5

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: "intl, mbstring, pdo_sqlite, zip"
                  php-version: 8.5
                  tools: composer:v2

            - name: "Cache Composer dependencies"
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache
                  key: composer-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-

            - name: "Install dependencies"
              run: composer install --ansi --no-interaction --no-progress --prefer-dist

            - name: "Run tests"
              run: vendor/bin/phpunit
